Updatecheck: false
World: 'world'
BungeeCord: true
Tablist: true
Addons: true
ConsoleCommands: false
DisabledCommands: 3
FalseCommands: 3
Shop: false
ReplaceUmlauts: false
MySQL:
  CurrentVersion: -1
  Enabled: false
  Port: 3306
  Host: 'localhost'
  Database: 'database'
  Username: 'root'
  Password: 'password'